apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: agent
      image: gcr.io/rpa-devops/jenkins-agent
      command:
        - sleep
      args:
        - 99d
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375

